# Generated by Django 2.2.1 on 2019-05-07 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_children', to='wagtailcore.Site')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inheritance_info', to='wagtailcore.Site')),
            ],
        ),
    ]
