# Generated by Django 2.2.4 on 2019-09-07 08:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail_site_inheritance.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_site_inheritance.models.PageInheritanceMixin, 'wagtailcore.page'),
        ),
    ]
