# Generated by Django 2.2.5 on 2019-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_otherpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpage',
            name='custom_content',
            field=models.CharField(default='', max_length=500),
        ),
    ]
