name: Python Tests

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install tox
    - name: Validate formatting
      run: tox -e format

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.8", "3.9", "3.10"]
        django: ["3.2", "4.0"]
        wagtail: ["2.16", "3.0"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip tox
    - name: Test with tox
      run: tox
      env:
        TOXENV: py${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}
    - name: Prepare artifacts
      run: mkdir .coverage-data && mv .coverage.* .coverage-data/
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-data
        path: .coverage-data/

  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v3
      with:
        name: coverage-data
        path: .
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install --upgrade pip coverage[toml]
    - name: Prepare Coverage report
      run: |
        coverage combine
        coverage xml
        coverage report -m --skip-covered
